[build-system]
requires = ["setuptools>=45", "wheel", "cmake>=3.15"]
build-backend = "setuptools.build_meta"

[project]
name = "fst24_python"
version = "0.1.0"
description = "Modern Python interface for FST24 file format"
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
license = {text = "LGPL-2.1-or-later"}
requires-python = ">=3.7"
dependencies = [
    "numpy>=1.20",
    "polars>=0.20",
    "xarray>=2023.1",
    "typing_extensions>=4.0.0",
    "dataclasses>=0.8;python_version<'3.7'"
]

[project.optional-dependencies]
test = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
    "pytest-benchmark>=4.0"
]
docs = [
    "sphinx>=7.0",
    "sphinx-rtd-theme>=1.0",
    "sphinx-autodoc-typehints>=1.0"
]

[tool.setuptools]
packages = ["fst24"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "--cov=fst24 --cov-report=term-missing"

[tool.mypy]
python_version = "3.7"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
